export { default as AreaFormDialog } from './area-form/area-form.vue'; //项目表单
export { default as ProjectFormDialog } from './project-form/project-form.vue'; //项目表单
export { default as ClusterFormDialog } from './cluster-form/cluster-form.vue'; //组团表单
export { default as BuildingFormDialog } from './building-form/building-form.vue'; //楼栋表单
export { default as UnitFormDialog } from './unit-form/unit-form.vue'; //单元表单
export { default as RoomFormDialog } from './room-form/room-form.vue'; //房间表单
export { default as GarageFormDialog } from './garage-form/garage-form.vue'; //车库表单
export { default as CarportFormDialog } from './carport-form/carport-form.vue'; //车位表单
export { default as PublicAreaFormDialog } from './publicArea-form/publicArea-form.vue'; //公共区域表单
